language: python
dist: focal
python:
  - "3.9"
virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
      - git
      - python3-toml
      - python3-xdg

script: python3 -m unittest

notifications:
  email: false
